version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mysystem
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  db_data: 